apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-user-operator-tenant-a
  namespace: kafka-system
  labels:
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/part-of: multi-tenant-flink-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-user-operator-tenant-b
  namespace: kafka-system
  labels:
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/part-of: multi-tenant-flink-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: strimzi-user-operator-kafka-secrets
  namespace: kafka-system
  labels:
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/part-of: multi-tenant-flink-platform
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-user-operator-tenant-a-kafka-secrets
  namespace: kafka-system
  labels:
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/part-of: multi-tenant-flink-platform
subjects:
  - kind: ServiceAccount
    name: strimzi-user-operator-tenant-a
    namespace: kafka-system
roleRef:
  kind: Role
  name: strimzi-user-operator-kafka-secrets
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-user-operator-tenant-b-kafka-secrets
  namespace: kafka-system
  labels:
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/part-of: multi-tenant-flink-platform
subjects:
  - kind: ServiceAccount
    name: strimzi-user-operator-tenant-b
    namespace: kafka-system
roleRef:
  kind: Role
  name: strimzi-user-operator-kafka-secrets
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: strimzi-user-operator
  namespace: tenant-a
  labels:
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/part-of: multi-tenant-flink-platform
rules:
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkausers
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkausers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkausers/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-user-operator
  namespace: tenant-a
  labels:
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/part-of: multi-tenant-flink-platform
subjects:
  - kind: ServiceAccount
    name: strimzi-user-operator-tenant-a
    namespace: kafka-system
roleRef:
  kind: Role
  name: strimzi-user-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: strimzi-user-operator
  namespace: tenant-b
  labels:
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/part-of: multi-tenant-flink-platform
rules:
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkausers
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkausers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkausers/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-user-operator
  namespace: tenant-b
  labels:
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/part-of: multi-tenant-flink-platform
subjects:
  - kind: ServiceAccount
    name: strimzi-user-operator-tenant-b
    namespace: kafka-system
roleRef:
  kind: Role
  name: strimzi-user-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-user-operator-tenant-a
  namespace: kafka-system
  labels:
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/name: strimzi-user-operator
    app.kubernetes.io/part-of: multi-tenant-flink-platform
    platform.example.com/tenant: tenant-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: strimzi-user-operator
      platform.example.com/tenant: tenant-a
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: flink-platform
        app.kubernetes.io/name: strimzi-user-operator
        app.kubernetes.io/part-of: multi-tenant-flink-platform
        platform.example.com/tenant: tenant-a
        strimzi.io/name: flink-platform-kafka-entity-operator
    spec:
      serviceAccountName: strimzi-user-operator-tenant-a
      containers:
        - name: strimzi-user-operator
          image: quay.io/strimzi/operator:1.1.0
          imagePullPolicy: IfNotPresent
          args:
            - /opt/strimzi/bin/user_operator_run.sh
          env:
            - name: STRIMZI_NAMESPACE
              value: tenant-a
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: flink-platform-kafka-kafka-bootstrap.kafka-system.svc:9091
            - name: STRIMZI_LABELS
              value: strimzi.io/cluster=flink-platform-kafka,platform.example.com/owner-team=tenant-a
            - name: STRIMZI_CA_NAMESPACE
              value: kafka-system
            - name: STRIMZI_CA_CERT_NAME
              value: flink-platform-kafka-clients-ca-cert
            - name: STRIMZI_CA_KEY_NAME
              value: flink-platform-kafka-clients-ca
            - name: STRIMZI_CLUSTER_CA_CERT_SECRET_NAME
              value: flink-platform-kafka-cluster-ca-cert
            - name: STRIMZI_EO_KEY_SECRET_NAME
              value: flink-platform-kafka-entity-user-operator-certs
            - name: STRIMZI_EO_KEY_NAME
              value: entity-operator.key
            - name: STRIMZI_EO_CERT_NAME
              value: entity-operator.crt
            - name: STRIMZI_ACLS_ADMIN_API_SUPPORTED
              value: "true"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_GC_LOG_ENABLED
              value: "false"
            - name: STRIMZI_CA_VALIDITY
              value: "365"
            - name: STRIMZI_CA_RENEWAL
              value: "30"
            - name: STRIMZI_PKCS12_KEYSTORE_GENERATION
              value: "true"
          ports:
            - containerPort: 8081
              name: healthcheck-uou
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthy
              port: healthcheck-uou
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: healthcheck-uou
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: strimzi-uou-tmp
              mountPath: /tmp
      volumes:
        - name: strimzi-uou-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 5Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-user-operator-tenant-b
  namespace: kafka-system
  labels:
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/name: strimzi-user-operator
    app.kubernetes.io/part-of: multi-tenant-flink-platform
    platform.example.com/tenant: tenant-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: strimzi-user-operator
      platform.example.com/tenant: tenant-b
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: flink-platform
        app.kubernetes.io/name: strimzi-user-operator
        app.kubernetes.io/part-of: multi-tenant-flink-platform
        platform.example.com/tenant: tenant-b
        strimzi.io/name: flink-platform-kafka-entity-operator
    spec:
      serviceAccountName: strimzi-user-operator-tenant-b
      containers:
        - name: strimzi-user-operator
          image: quay.io/strimzi/operator:1.1.0
          imagePullPolicy: IfNotPresent
          args:
            - /opt/strimzi/bin/user_operator_run.sh
          env:
            - name: STRIMZI_NAMESPACE
              value: tenant-b
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: flink-platform-kafka-kafka-bootstrap.kafka-system.svc:9091
            - name: STRIMZI_LABELS
              value: strimzi.io/cluster=flink-platform-kafka,platform.example.com/owner-team=tenant-b
            - name: STRIMZI_CA_NAMESPACE
              value: kafka-system
            - name: STRIMZI_CA_CERT_NAME
              value: flink-platform-kafka-clients-ca-cert
            - name: STRIMZI_CA_KEY_NAME
              value: flink-platform-kafka-clients-ca
            - name: STRIMZI_CLUSTER_CA_CERT_SECRET_NAME
              value: flink-platform-kafka-cluster-ca-cert
            - name: STRIMZI_EO_KEY_SECRET_NAME
              value: flink-platform-kafka-entity-user-operator-certs
            - name: STRIMZI_EO_KEY_NAME
              value: entity-operator.key
            - name: STRIMZI_EO_CERT_NAME
              value: entity-operator.crt
            - name: STRIMZI_ACLS_ADMIN_API_SUPPORTED
              value: "true"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_GC_LOG_ENABLED
              value: "false"
            - name: STRIMZI_CA_VALIDITY
              value: "365"
            - name: STRIMZI_CA_RENEWAL
              value: "30"
            - name: STRIMZI_PKCS12_KEYSTORE_GENERATION
              value: "true"
          ports:
            - containerPort: 8081
              name: healthcheck-uou
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthy
              port: healthcheck-uou
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: healthcheck-uou
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: strimzi-uou-tmp
              mountPath: /tmp
      volumes:
        - name: strimzi-uou-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 5Mi
