tenantName: tenant-b
namespace: tenant-b

image:
  repository: ghcr.io/faezeh-kianimoravej/tenant-b-flink-job
  tag: 3fdc58f483a5a1fe2b7750212e188f77a32121c6
  pullPolicy: IfNotPresent

flinkVersion: v1_19

job:
  className: com.example.tenantb.OrdersEnrichmentJob
  jarURI: local:///opt/flink/usrlib/tenant-b-flink-job.jar
  parallelism: 1
  restartNonce: 1

kafka:
  bootstrapServers: kafka:9092
  inputTopics:
    - tenant-b-orders
    - tenant-b-customers
  outputTopic: tenant-b-enriched-orders
  consumerGroupId: tenant-b-flink-job

checkpointing:
  interval: 30s
