apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: tenant-a-flink-user
  namespace: tenant-a
  labels:
    strimzi.io/cluster: flink-platform-kafka
    app.kubernetes.io/managed-by: flink-platform
    app.kubernetes.io/part-of: multi-tenant-flink-platform
    platform.example.com/application-id: APP-TENANT-A
    platform.example.com/owner-team: tenant-a
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: tenant-a-orders
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
      - resource:
          type: topic
          name: tenant-a-customers
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
      - resource:
          type: topic
          name: tenant-a-enriched-orders
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
      - resource:
          type: group
          name: tenant-a-console-test
          patternType: literal
        operations:
          - Read
          - Describe
      - resource:
          type: group
          name: tenant-a-flink-job
          patternType: literal
        operations:
          - Read
          - Describe
      - resource:
          type: group
          name: tenant-a-flink-job-customers
          patternType: literal
        operations:
          - Read
          - Describe
