tenantName: tenant-a
namespace: tenant-a

image:
  repository: ghcr.io/faezeh-kianimoravej/tenant-a-flink-job
  tag: 21376fcf70d31c0f41679066eaa4ca6cea1cd52e
  pullPolicy: IfNotPresent

flinkVersion: v2_2

job:
  className: com.example.tenanta.TenantAFlinkJobApplication
  jarURI: local:///opt/flink/usrlib/tenant-a-flink-job.jar
  parallelism: 1
  restartNonce: 7

kafka:
  bootstrapServers: flink-platform-kafka-kafka-bootstrap.kafka-system.svc.cluster.local:9092
  inputTopics:
    - tenant-a-orders
    - tenant-a-customers
  outputTopic: tenant-a-enriched-orders
  consumerGroupId: tenant-a-flink-job
  security:
    enabled: true
    protocol: SASL_PLAINTEXT
    saslMechanism: SCRAM-SHA-512
    userSecretName: tenant-a-flink-user
    usernameKey: username
    passwordKey: password

governance:
  applicationId: APP-TENANT-A
  ownerTeam: tenant-a
  kafkaUser: tenant-a-flink-user

checkpointing:
  interval: 30s
