tenantName: tenant-a
namespace: tenant-a

image:
  repository: ghcr.io/faezeh-kianimoravej/tenant-a-flink-job
  # Replace with the immutable Git SHA tag promoted to production.
  tag: TODO_REPLACE_WITH_TENANT_A_COMMIT_SHA
  pullPolicy: IfNotPresent

flinkVersion: v2_2

job:
  className: com.example.tenanta.TenantAFlinkJobApplication
  jarURI: local:///opt/flink/usrlib/tenant-a-flink-job.jar
  parallelism: 2
  restartNonce: 1

kafka:
  bootstrapServers: flink-platform-kafka-kafka-bootstrap.kafka-system.svc.cluster.local:9092
  inputTopics:
    - tenant-a-orders
    - tenant-a-customers
  outputTopic: tenant-a-enriched-orders
  consumerGroupId: tenant-a-flink-job

checkpointing:
  interval: 120s
